# -*- python -*-
Import("env")

env.Program(["lsstdata01.cc"], LIBS=env.getLibs("main test"))

#
# Tests
#
import lsst.scons.tests

tests = lsst.scons.tests.Control(env, verbose = True)
tests.run("lsstdata01.cc")

#for target in tests.run("*.py"):
#    env.Depends(target,
#                "#lsst/daf/data/_data%s" % (mod, env['LDMODULESUFFIX']))
