# -*- python -*-
Import('env')

import lsst.scons.tests

tests = lsst.scons.tests.Control(env, ignoreList=[], verbose=True)

tests.run("*.cc")

for target in tests.run("*.py"):
    env.Depends(target, "#python")
