# -*- python -*-
Import('env')
import os

env.SharedLibrary('bputils', 
                  Glob("../src/*.cc") + Glob("../src/numpy/*.cpp") + Glob("../src/const_aware/*.cpp"), 
                  LIBS=env.getpylibs("python boost_python numpy"))
